[package]
name = "rustplatform"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
diesel = { version = "2.0.0", features = ["postgres","chrono", "serde_json","time"] }
serde = { version = "1.0", features = ["derive"] }
dotenvy = "0.15"
serde_json = "1.0"
rocket =  {version = "0.5.0-rc.2" , features = ["secrets","json"]}
testcontainers = "0.14.0"
chrono = {version = "0.4.3",features = ["serde"]}
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"] }

diesel_migrations = { version = "2.0.0", features = ["postgres"] }
diesel-derive-enum = { version = "2.0.0", features = ["postgres"] }


