[package]
name = "rustbase"
version = "0.0.1"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
diesel = { version = "2.0.0", features = ["postgres","chrono", "serde_json","time"] }
serde = { version = "1.0", features = ["derive"] }
dotenvy = "0.15"
serde_json = "1.0"
rocket = "0.4.11"
testcontainers = "0.14.0"
chrono = {version = "0.4.3",features = ["serde"]}

rocket_contrib = { version = "0.4.10" ,features = ["json","diesel_postgres_pool"]}
diesel_migrations = { version = "2.0.0", features = ["postgres"] }


