version: "3.8"
services:
  rust:
    container_name: rustplatform
    image: rustplatform
    depends_on:
      - mongo
    platform: linux/amd64
    build: .
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: users
      MONGO_INITDB_ROOT_PASSWORD: 12ed2342
      MONGO_INITDB_DATABASE: rustplatform
    volumes:
      - ./init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data:/data/db
