version: "3.8"
services:
  rust:
    container_name: rustplatform
    image: rustplatform
    depends_on:
      - sql
    platform: linux/amd64
    build: .
  sql:
    container_name: sql
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rustplatform
    volumes:
      - ./data:/var/lib/postgresql/data
