name: Bump version
on:
  workflow_dispatch:
  inputs:
     tag_code: ""
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create a GitHub release
        run: git tag -l ${{github.event.inputs.tag_code  }}
        run: git push
